### ISSUE TITLE
Emailing : développement et intégration

### ISSUE THREAD

**Issue by aznsilence** [hteumeuleu/foire-aux-livres#15]
Bonjour Rémi,

Tout d’abord merci pour cette généreuse initiative :)

Je souhaiterai adopter le livre "Emailing : développement et intégration" par Thomas Defossez.
J’ai lu sur l’autre ticket qu’il fallait envoyer un bon de livraison pour un envoi de 400g par courriel, est-ce 400g pour ce livre aussi ?

Encore merci,

Etienne

**Comment by hteumeuleu** [comment]
Salut,

Oui c'est bien ça, tu peux compter environ 400 grammes. Je te laisse éditer de ton côté le bon Mondial Relay ou Relais Colis avec ton adresse de destination. Et ensuite tu peux m'envoyer le bon de livraison par email à mon adresse _remi arobase hteumeuleu point fr_. Merci d'avance !
